"""user tokens

Revision ID: 71abc255b1d6
Revises: f084b078802d
Create Date: 2020-03-27 10:29:05.662855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71abc255b1d6'
down_revision = 'f084b078802d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
