version: '3'
services:
  microblog:
    build: ./microblog
    expose:
      - "8000"
    volumes:
      - /var/lib/docker/volumes/mb_v/_data:/db
    depends_on:
      - redis
  fake_email:
    build: ./fake_email_server
    container_name: fake_email
    ports:
      - "8025:8025"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.6.1"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  nginx:
    build: ./nginx
    ports:
      - "8000:8000"
    depends_on:
      - microblog
  redis:
    image: "redis"
    container_name: redis_work
    ports:
      - "6379:6379"
  rq_work:
    image: "services_microblog"
    entrypoint: ["rq", "worker", "--url", "redis://redis:6379", "microblog-tasks"]
    # if volumes is not defined here, the app.db file is empty
    volumes:
      - /var/lib/docker/volumes/mb_v/_data:/db
    depends_on:
      - redis
      - microblog
    links:
      - redis