version: '3'
services:
  microblog:
    build: ./microblog
    expose:
      - "8000"
    volumes:
      - /var/lib/docker/volumes/mb_v/_data:/db
  fake_email:
    build: ./fake_email_server
    container_name: fake_email
    ports:
      - "8025:8025"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.6.1"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
  nginx:
    build: ./nginx
    ports:
      - "8000:8000"
    depends_on:
      - microblog